### Learnings from this notebook: <br>
    - What are tensors? <br>
    - tensor.to(device) OR tensor.cpu() <br>
    - How to convert a 2D list into a tensor <br>
    - tensor indexing (very similar to numpy indexing) <br>
    - tensor and numpy conversions <br>

### What are the list of torch classes/sub-packages seen in this notebook? <br>  
 - `torch.cuda.is_available()` gives a boolean output
 - `torch.tensor(x)` <br>
  - x could be a 1D or 2D iterable (list or tuple) <br>
 - `torch.ones_like(tensor_variable)`, `torch.rand_like(tensor_variable)` <br>
 - `torch.ones(shape_in_a_tuple_or_list)` , `torch.zeros(shape_in_a_tuple_or_list)` and  `torch.rand(shape_in_a_tuple_or_list)` <br>
 - `torch_tensor_variable[start_index:end_index:step_value]` (similar to a numpy indexing)
 - numpy to torch tensor: `torch.from_numpy(np_array)`
 - torch_tensor to numpy: `torch_tensor_variable.numpy()`
 - Concatenate across rows `torch.cat((an_iterable_of_tensors),dim=0)`<br>
 - Concatenate across columns `torch.cat((an_iterable_of_tensors),dim=1)` <br>
 - tensor multiplication `tensor1 * tensor2 == torch.mul(tensor1,tensor2,out=tensor3) == tensor1.mul(tensor2)` <br>
 - convert single_element_tensor into a python datatype using `.item()` --> `single_element_tensor = tensor1.sum(); python_variable = single_element_tensor.item()` <br>
 - In-place Operations in torch using `_`: `x.add_(5)` will add 5 to each element of x <br>
 - tensor `n = t.numpy()` & np.add(n,2,out=n) --> A change in `n` will automatically change `t` (vice versa is true too)

Source of the notebooks of this course: [Link](https://docs.microsoft.com/en-us/learn/paths/pytorch-fundamentals/)

Source of this specific notebook: [Link](https://docs.microsoft.com/en-us/learn/modules/intro-machine-learning-pytorch/2-tensors?ns-enrollment-type=LearningPath&ns-enrollment-id=learn.pytorch.pytorch-fundamentals)

In [2]:
%matplotlib inline

In [3]:
import torch
import numpy as np

In [7]:
torch.ones((1,2,3))

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [4]:
torch.cuda.is_available()

True

What are **Tensors**?
- Tensors are `ndarrays` similar to numpy but optimzed to run in GPUs
- Tensors are also optimized for `automatic differentiation`

1. Tensors From Python lists

In [5]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(type(data))
print(type(x_data))

<class 'list'>
<class 'torch.Tensor'>


2. Tensors from Numpy Arrays

In [6]:
np_array = np.array(data)
print(type(np_array))
x_np = torch.from_numpy(np_array)
print(type(x_np))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


3. Tensors similar to another Tensor

In [6]:
x_ones = torch.ones_like(x_data)
print(type(x_ones))
print(x_ones)

<class 'torch.Tensor'>
tensor([[1, 1],
        [1, 1]])


In [7]:
# the below will throw an error as x_data dtype is Int (specifically, Long) 
# and random numbers canbot be generated in Int dtype
x_rand = torch.rand_like(x_data)
print(type(x_rand))
print(x_rand)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [8]:
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(type(x_rand))
print(x_rand)

<class 'torch.Tensor'>
tensor([[0.9470, 0.2274],
        [0.5498, 0.2070]])


Creating `Random` or `Constant` Tensors from a given **shape**

In [9]:
shape = (2,3)
x_ones = torch.ones(shape)
x_zeros = torch.zeros(shape)
x_rands = torch.rand(shape)

print(f"Ones:\n{x_ones}")
print(f"Zeros:\n{x_zeros}")
print(f"Random:\n{x_rands}")

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Random:
tensor([[0.1540, 0.0498, 0.0958],
        [0.7644, 0.0327, 0.6922]])


**Attributes** of a Tensor

In [7]:
tensor = torch.rand(4,5) 

print(f"Shape of Tensor:{tensor.shape}") 
print(f"Datatype of Tensor:{tensor.dtype}")
print(f"Device where the Tensor is stored:{tensor.device}")

Shape of Tensor:torch.Size([4, 5])
Datatype of Tensor:torch.float32
Device where the Tensor is stored:cpu


Change the device to `cuda`

In [8]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
print(f"Device where the Tensor is stored:{tensor.device}")

Device where the Tensor is stored:cuda:0


In [11]:
tensor

tensor([[0.7227, 0.0191, 0.9136, 0.3873, 0.6656],
        [0.3693, 0.1062, 0.0766, 0.2567, 0.4990],
        [0.3791, 0.2940, 0.8401, 0.5817, 0.4946],
        [0.4029, 0.3215, 0.3802, 0.7170, 0.9948]], device='cuda:0')

In [10]:
tensor[1,:]

tensor([0.3693, 0.1062, 0.0766, 0.2567, 0.4990], device='cuda:0')

In [12]:
tensor.cpu()[1,:]

tensor([0.3693, 0.1062, 0.0766, 0.2567, 0.4990])

In [15]:
!which python

/opt/conda/bin/python


In [13]:
tensor[-1::]

tensor([[0.4029, 0.3215, 0.3802, 0.7170, 0.9948]], device='cuda:0')

In [18]:
tensor[-1::]

tensor([], device='cuda:0', size=(0, 5))

In [14]:
tensor[:-1:]

tensor([[0.7227, 0.0191, 0.9136, 0.3873, 0.6656],
        [0.3693, 0.1062, 0.0766, 0.2567, 0.4990],
        [0.3791, 0.2940, 0.8401, 0.5817, 0.4946]], device='cuda:0')

In [15]:
tensor[:-1:2]

tensor([[0.7227, 0.0191, 0.9136, 0.3873, 0.6656],
        [0.3791, 0.2940, 0.8401, 0.5817, 0.4946]], device='cuda:0')

concatenating tensors

In [16]:
help(torch.cat)

Help on built-in function cat:

cat(...)
    cat(tensors, dim=0, *, out=None) -> Tensor
    
    Concatenates the given sequence of :attr:`seq` tensors in the given dimension.
    All tensors must either have the same shape (except in the concatenating
    dimension) or be empty.
    
    :func:`torch.cat` can be seen as an inverse operation for :func:`torch.split`
    and :func:`torch.chunk`.
    
    :func:`torch.cat` can be best understood via examples.
    
    Args:
        tensors (sequence of Tensors): any python sequence of tensors of the same type.
            Non-empty tensors provided must have the same shape, except in the
            cat dimension.
        dim (int, optional): the dimension over which the tensors are concatenated
    
    Keyword args:
        out (Tensor, optional): the output tensor.
    
    Example::
    
        >>> x = torch.randn(2, 3)
        >>> x
        tensor([[ 0.6580, -1.0969, -0.4614],
                [-0.1034, -0.5790,  0.1497]])
        >>

In [35]:
x = torch.randn(2, 3)
concatenated_x_across_rows = torch.cat([x,x],dim=0)
concatenated_x_across_columns = torch.cat([x,x],dim=1)
assert concatenated_x_across_rows.shape == (4,3)
assert concatenated_x_across_columns.shape == (2,6)

In [37]:
print(x)

tensor([[-0.8546,  1.1102, -0.2373],
        [ 1.5505, -0.1730,  2.2415]])


In [36]:
print(concatenated_x_across_rows)

tensor([[-0.8546,  1.1102, -0.2373],
        [ 1.5505, -0.1730,  2.2415],
        [-0.8546,  1.1102, -0.2373],
        [ 1.5505, -0.1730,  2.2415]])


Arithmetic Operations

In [38]:
# how to matrix multiplication
y = x @ x.T
print(y.shape)

torch.Size([2, 2])


In [39]:
# how we cannot do matrix multiplication
y = x @ x
print(y.shape)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [49]:
# element-wise multiplication
tensor1 = torch.rand(2,2)
tensor2 = torch.ones(2,2)
z1 = tensor1 * tensor2
z2 = tensor1.mul(tensor2)

In [52]:
tensor1, tensor2

(tensor([[0.3411, 0.2054],
         [0.7271, 0.8197]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [53]:
z1

tensor([[0.3411, 0.2054],
        [0.7271, 0.8197]])

In [54]:
z2

tensor([[0.3411, 0.2054],
        [0.7271, 0.8197]])

In [57]:
# initialize a tensor with random values first
# z3 = torch.rand(tensor.shape)
z3 = torch.mul(tensor1, tensor2, out=z3)

In [58]:
z3

tensor([[0.3411, 0.2054],
        [0.7271, 0.8197]])

Single-element tensors

`item()` -- to convert single element tensors into python numerical values

In [59]:
agg = tensor1.sum()
print(type(agg))
print(agg.shape)
agg_item = agg.item()
print(type(agg_item))

<class 'torch.Tensor'>
torch.Size([])
<class 'float'>


In [60]:
agg

tensor(2.0933)

In [61]:
agg_item

2.093311309814453

In-place operations

In [62]:
print(tensor,"\n")
tensor.add_(5) # similar to pandas argument `inplace=True`

tensor([[0.8197, 0.8177],
        [0.1233, 0.4900]]) 



tensor([[5.8197, 5.8177],
        [5.1233, 5.4900]])

In [63]:
print(tensor)

tensor([[5.8197, 5.8177],
        [5.1233, 5.4900]])


Numpy related Array

In [64]:
t = torch.ones(5)

In [65]:
n = t.numpy()

In [66]:
print(type(t))
print(type(n))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [67]:
print(t.add_(1))
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


A change in `t` tensor reflects in `n` numpy

changes in numpy array reflects in tensor too

In [68]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]
